name: Laravel CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

    - name: Generate Laravel key
      run: php artisan key:generate

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

  lint:
    name: PHP lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

    - name: Check coding standards
      run: vendor/bin/phpcs

  # Add more jobs here for other tasks like deployment
